function [axplot,axlegend]=FigurePanels(num)
figure(num);
hp = uipanel('Title','Main Panel','FontSize',12,...
                'BackgroundColor','white',...
                'Position',[0 0 1 .67]);
hplegend = uipanel('Title','Legend Panel','FontSize',12,...
                'BackgroundColor',[0.95,0.95,0.95],...
                'Position',[0 0.67 1 0.33]);
axplot=axes('Parent',hp,'Position',[0.1 0.1 0.8 0.8]);
axlegend=axes('Parent',hplegend,'Position',[0.1 0.1 0.8 0.8],'Visible','Off','Box','On');
end